FROM registry.access.redhat.com/ubi9/python-39

ENV CONDA_DIR=/opt/app-root/src/conda
ENV CONDA_BIN=${CONDA_DIR}/bin/conda
ENV PATH=/opt/app-root/src/bin:$PATH

# Conda makes the installation of ffmpeg less painful
RUN wget -q https://repo.anaconda.com/miniconda/Miniconda3-py39_23.1.0-1-Linux-x86_64.sh -O conda_install.sh && \
    /bin/bash ~/conda_install.sh -b -p ${CONDA_DIR}

COPY environment.yml .

RUN ${CONDA_BIN} env create -f environment.yml

COPY . .

USER root
RUN chown default .tmp && chmod -R 777 .tmp
USER default

EXPOSE 5000
ENV NUMBA_CACHE_DIR /opt/app-root/src/.tmp

CMD ${CONDA_BIN} run -n rhods-sound-classification-webapp-backend --no-capture-output \
    flask run --host=0.0.0.0