apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rhods-sound-classification-web-backend
    app.kubernetes.io/part-of: rhods-sound-classification-web-app
  name: rhods-sound-classification-web-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhods-sound-classification-web-backend
  template:
    metadata:
      labels:
        app: rhods-sound-classification-web-backend
    spec:
      containers:
        - image: quay.io/jramcast/rhods-sound-classification-web-backend:latest
          imagePullPolicy: Always
          name: rhods-sound-classification-web-backend
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: INFERENCE_ENDPOINT
              value: to-be-defined
