apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  type: NodePort
  ports:
    - name: 5000-tcp
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: webapp