FROM registry.access.redhat.com/ubi9/python-39

COPY requirements.txt .

RUN pip install --upgrade pip==23.1.2 && \
    pip install -r requirements.txt

COPY . .

VOLUME [ "/data" ]

ENTRYPOINT ["python", "main.py"]
